server:
  port: 9001

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://connectwithus.site:3306/withus
    username: withus
    password: withus
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 160086760593-ocfit5qtj8vainl0afo329ikgq5n1j2f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://connectwithus.site/google
            scope:
              - email
              - profile

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Multipart 설정
  servlet:
    multipart:
      max-file-size: 100MB # 요청한 파일 한 개의 크기
      max-request-size: 100MB # 요청한 파일 전체의 크기

kakao:
  rest-api-key: 7ea82d8a610fe51bcf3eca267069b264
  redirect-uri: https://connectwithus.site/kakao
#  redirect-uri: http://localhost:9001/api/oauth/kakao


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: withus.bucket
    credentials:
      access-key: AKIASQ5NU6QBBSXRE6WD
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false