server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 160086760593-ocfit5qtj8vainl0afo329ikgq5n1j2f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:9001/api/oauth/google
            scope:
              - email
              - profile

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kakao:
  rest-api-key: 7ea82d8a610fe51bcf3eca267069b264
  redirect-uri: http://localhost:9001/api/oauth/kakao

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace